# Generated by Django 5.2.1 on 2025-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image (1200x800px)', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Secondary image (600x400px)', null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
