# Generated by Django 5.2.1 on 2025-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('services', 'Services'), ('products', 'Products'), ('about', 'About Us'), ('contact', 'Contact Us')], max_length=20, unique=True)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
