# Generated by Django 5.2.1 on 2025-05-16 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0002_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text',
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_cta_link',
            field=models.CharField(blank=True, help_text='URL for primary button', max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_cta_text',
            field=models.CharField(blank=True, help_text="Main button text (e.g. 'Get Started')", max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_cta_link',
            field=models.CharField(blank=True, help_text='URL for secondary button', max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='herosection',
            name='secondary_cta_text',
            field=models.CharField(blank=True, help_text="Secondary button text (e.g. 'Learn More')", max_length=50),
        ),
    ]
