# Generated by Django 5.2.1 on 2025-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0002_remove_aboutsection_image_aboutsection_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
