# Generated by Django 5.2.1 on 2025-05-28 01:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0003_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main image (1200x800px)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='secondary_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Secondary image (600x400px)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_360',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Optimal size: 600x600px (1:1 ratio)', max_length=255, verbose_name='image'),
        ),
    ]
