# Generated by Django 5.2.1 on 2025-05-16 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0003_remove_herosection_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='primary_cta_link',
            field=models.CharField(blank=True, help_text="Enter either: (1) URL name like 'services', (2) Path like '/services/', or (3) Full URL", max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_cta_link',
            field=models.CharField(blank=True, help_text="Enter either: (1) URL name like 'services', (2) Path like '/services/', or (3) Full URL", max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
