# Generated by Django 5.2.1 on 2025-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0004_alter_aboutsection_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image (1200x800px)', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Secondary image (600x400px)', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo',
            field=models.ImageField(upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=models.ImageField(upload_to='navbar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='products/360/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Optimal size: 600x600px (1:1 ratio)', upload_to='team/'),
        ),
    ]
