# Generated by Django 5.2.1 on 2025-05-16 14:10

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0004_alter_herosection_primary_cta_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_cta_link',
            field=models.CharField(blank=True, help_text="Examples:<br>- URL name: 'services'<br>- Path: '/services/'<br>- Full URL: 'https://example.com'", max_length=200, validators=[django.core.validators.RegexValidator(message="Enter either: (1) URL name (e.g. 'services'), (2) Path (e.g. '/services/'), or (3) Full URL", regex='^(https?://|/|[\\w-]+$)')]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_cta_link',
            field=models.CharField(blank=True, help_text="Examples:<br>- URL name: 'services'<br>- Path: '/services/'<br>- Full URL: 'https://example.com'", max_length=200, validators=[django.core.validators.RegexValidator(message="Enter either: (1) URL name (e.g. 'services'), (2) Path (e.g. '/services/'), or (3) Full URL", regex='^(https?://|/|[\\w-]+$)')]),
        ),
    ]
