# Generated by Django 5.2.1 on 2025-06-01 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0005_alter_aboutsection_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='secondary_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='secondary_image'),
        ),
    ]
