# Generated by Django 5.2.1 on 2025-06-01 21:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0006_alter_aboutsection_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_360',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_360'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
