# Generated by Django 5.2.1 on 2025-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0006_demobooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(help_text='Optimal size: 1200x800px', upload_to='about/')),
                ('meta_title', models.CharField(blank=True, help_text='Title for SEO (60 chars max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Description for SEO (160 chars max)', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(help_text='Optimal size: 600x600px (1:1 ratio)', upload_to='team/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for accessibility & SEO', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
