# Generated by Django 5.2.1 on 2025-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0007_aboutsection_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
