# Generated by Django 5.2.1 on 2025-05-17 18:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0008_alter_aboutsection_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
