# Generated by Django 5.2.1 on 2025-05-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0012_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to='products/360/'),
        ),
    ]
