# Generated by Django 5.2.1 on 2025-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0013_product_image_360'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='show_on_about',
            field=models.BooleanField(default=True, help_text='Toggle to display this member on the About page', verbose_name='Show on About Page'),
        ),
    ]
