# Generated by Django 5.2.1 on 2025-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rearm', '0014_teammember_show_on_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leadership/')),
                ('home_excerpt', models.TextField(help_text='Short message for homepage', max_length=200)),
                ('full_bio', models.TextField(help_text='Full bio for about page')),
                ('is_ceo', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Leadership Team',
                'ordering': ['display_order'],
            },
        ),
    ]
